import { DefaultTheme } from "styled-components/native";
export const BaseTheme: DefaultTheme = {
  colors: {
    primary: {
      dark: "#222222",
      brand: "#c12822",
      light: "#ffffff",
    },
    accent: {
      success: "#339933",
      error: "#cc0000",
      warning: "#ffcc00",
    },
    neutral: {
      grey10: "#e5e5e5",
      grey20: "#dbdbdc",
      grey40: "#b6b7ba",
      grey60: "#64676e",
      black: "#000000",
    },
    opaque: {
      white20: "#ffffff33",
      black20: "#00000033",
      black40: "#00000066",
    },
  },
  fonts: ["Museo-300", "Museo-700"],
  fontSizes: [10, 12, 14, 16, 18, 24, 28, 32],
  fontWeights: [400, 500, 700],
  letterSpacings: [0],
  typography: {
    Headline: {
      H3: {
        fontFamily: "Museo-700",
        fontSize: 16,
        fontWeight: 500,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 24,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
      H1: {
        fontFamily: "Museo-700",
        fontSize: 24,
        fontWeight: 500,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 36,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
      HS: {
        fontFamily: "Museo-900",
        fontSize: 28,
        fontWeight: 500,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 56,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
      H2: {
        fontFamily: "Museo-700",
        fontSize: 20,
        fontWeight: 500,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 32,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
      H4: {
        fontFamily: "Museo-700",
        fontSize: 14,
        fontWeight: 500,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 20,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
    },
    Paragraph: {
      P1: {
        fontFamily: "Museo-300",
        fontSize: 16,
        fontWeight: 400,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 20,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
      P2: {
        fontFamily: "Museo-300",
        fontSize: 15,
        fontWeight: 400,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 18,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
    },
    Labels: {
      L1: {
        fontFamily: "Museo-300",
        fontSize: 12,
        fontWeight: 400,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 18,
        textAlign: "left",
        textTransform: "none",
        textDecoration: "none",
      },
      L2: {
        fontFamily: "Museo-300",
        fontSize: 11,
        fontWeight: 500,
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 11.71875,
        textAlign: "left",
        textTransform: "uppercase",
        textDecoration: "none",
      },
    },
  },
  space: {
    "0": 0,
    XS: 4,
    S: 8,
    M: 16,
    L: 20,
  },
  radii: {
    "0": 0,
    S: 4,
    M: 8,
    L: 16,
  },
};
